Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  nodes = {
    "web1" => "192.168.56.11",
    "web2" => "192.168.56.12",
    "web3" => "192.168.56.13",
    "web4" => "192.168.56.14",
    "lb" => "192.168.56.20",
    "monitor" => "192.168.56.30"
  }

  nodes.each do |name, ip|
    config.vm.define name do |node|
      node.vm.hostname = name
      node.vm.network "private_network", ip: ip

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 2
      end
    end
  end

end
