---
- name: Install Node Exporter on all servers
  hosts: all
  become: yes

  tasks:

    - name: Update apt packages
      apt:
        update_cache: yes

    - name: Install Node Exporter
      apt:
        name: prometheus-node-exporter
        state: present

    - name: Ensure Node Exporter is running
      service:
        name: prometheus-node-exporter
        state: started
        enabled: yes
